/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Categoria;
import Dominio.Raza;
import Dominio.Tambo;
import Dominio.Usuario;
import Dominio.Vaca;
import Presentacion.ModelosCbox.ModeloCbCategoria;
import Presentacion.ModelosCbox.ModeloCbRaza;
import Presentacion.ModelosTbl.ModeloTblVacas;
import static java.awt.image.ImageObserver.ABORT;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Negro
 */
public class ManejoVacas extends javax.swing.JFrame {
    private static Tambo controladora;
    
    private static ArrayList<Categoria> categorias;
    private static ArrayList<Raza> razas;
    private static ManejoVacas instancia = null;
    
    private static ModeloTblVacas modeloTabla;
    private static Vaca vacaSeleccionada;
    private static ListSelectionModel lsmVacas;
    
    static Date fechaActual = null;
    static GregorianCalendar gc = new GregorianCalendar();
    static SimpleDateFormat formatFecha = new SimpleDateFormat("yyyy/MM/dd");
    /**
     * Creates new form ManejoVacas
     */
    public ManejoVacas() throws SQLException {
        initComponents();
        controladora = Tambo.getInstancia();
        cargarDdlRaza();
        cargarDdlCategoria();
        cargarDdlRaza();
        cargarTabla();
        setFechaActualCalendar();       
        
        lsmVacas = tblVacas.getSelectionModel();
        lsmVacas.addListSelectionListener(new ListenerCliente());
        tblVacas.setSelectionModel(lsmVacas);
    }

    public static ManejoVacas getInstancia(Usuario usuario) throws SQLException{
        if(instancia == null){
            instancia = new ManejoVacas();
        }
        return instancia;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarNuevo = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarCambios = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        ddlCategoria = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVacas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCaravana = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ddlRaza = new javax.swing.JComboBox();
        clFecha = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregarNuevo.setText("Agregar Nuevo");
        btnAgregarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Categoría de leche");

        btnGuardarCambios.setText("Guardar Cambios");
        btnGuardarCambios.setEnabled(false);
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        ddlCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblVacas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVacas);

        jLabel1.setText("Caravana");

        jLabel2.setText("Peso");

        txtCaravana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCaravanaMousePressed(evt);
            }
        });

        jLabel3.setText("Raza");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ddlRaza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Fecha de Nacimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCaravana)
                            .addComponent(txtPeso)
                            .addComponent(ddlCategoria, 0, 163, Short.MAX_VALUE)
                            .addComponent(ddlRaza, 0, 163, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarCambios)
                            .addComponent(btnCancelar)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregarNuevo))))
                .addContainerGap())
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMensaje)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblMensaje)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCaravana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(ddlRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ddlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAgregarNuevo)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardarCambios)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)))))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNuevoActionPerformed
        if(!faltanDatos()){
            if(!existe(Integer.parseInt(txtCaravana.getText()))){//un int no da para el RUT
                Vaca vaca = new Vaca();
                Categoria categoria = new Categoria();
                Raza raza = new Raza();
                vaca.setCaravana(txtCaravana.getText());
                vaca.setPeso(Integer.parseInt(txtPeso.getText()));
                vaca.setFechaNacimiento(fechaActual);
                categoria.setId(ddlCategoria.getSelectedIndex()+1);
                vaca.setCategoria(categoria);
                raza.setId(ddlRaza.getSelectedIndex()+1);
                vaca.setRaza(raza);

                controladora.altaVaca(vaca);
                limpiar();
                cargarTabla();
            }else{
                //sout : si estado = 0 { cambiar estado en la bbdd a 1}
            }
        }else{
            this.lblMensaje.setText("Faltan ingresar datos");
        }
    }//GEN-LAST:event_btnAgregarNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        btnAgregarNuevo.setEnabled(true);
        btnGuardarCambios.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
        ddlCategoria.setEnabled(true);
        ddlRaza.setEnabled(true);
        cargarTabla();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        int seleccion = tblVacas.getSelectedRow();
        if (seleccion != -1) {
            Vaca unaVaca = new Vaca();
            unaVaca.setId(vacaSeleccionada.getId());
            unaVaca.setCaravana(txtCaravana.getText());
            unaVaca.setPeso(Integer.parseInt(txtPeso.getText()));
            controladora.modificarVaca(unaVaca);
        }
        limpiar();
        cargarTabla();
        btnAgregarNuevo.setEnabled(true);
        btnGuardarCambios.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
        ddlCategoria.setEnabled(true);
        ddlRaza.setEditable(true);
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int seleccion = tblVacas.getSelectedRow();
        if (seleccion != -1) {
            controladora.bajaVaca(vacaSeleccionada.getId());
        }
        cargarTabla();
        btnAgregarNuevo.setEnabled(true);
        btnGuardarCambios.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnCancelar.setEnabled(false);
        ddlCategoria.setEnabled(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCaravanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCaravanaMousePressed
        this.lblMensaje.setText("");
    }//GEN-LAST:event_txtCaravanaMousePressed

    private boolean faltanDatos(){
        return txtCaravana.getText().equals("") || txtPeso.getText().equals("");
    }
    private boolean existe(int caravanaVaca){
        Vaca vaca;
        vaca = controladora.buscarVaca(caravanaVaca);
        return vaca != null;
    }
    private void cargarDdlCategoria() throws SQLException{
        ModeloCbCategoria categorias = new ModeloCbCategoria(controladora.listarCategorias());
        this.ddlCategoria.setModel(categorias);
        this.ddlCategoria.setSelectedIndex(-1);
    }
    private void cargarDdlRaza() throws SQLException{
        ModeloCbRaza razas = new ModeloCbRaza(controladora.listarRazas());
        this.ddlRaza.setModel(razas);
        this.ddlRaza.setSelectedIndex(-1);
    }
    private void limpiar(){
        this.txtCaravana.setText("");
        this.txtPeso.setText("");
        this.ddlCategoria.setSelectedIndex(-1);
        this.ddlRaza.setSelectedIndex(-1);
        setFechaActualCalendar();
    }
    private void cargarTabla(){
        List<Vaca> vacas = controladora.listarVacas();
        modeloTabla = new ModeloTblVacas(vacas);
        tblVacas.setModel(modeloTabla);
    }
    private void setFechaActualCalendar(){
        fechaActual = new Date();
        clFecha.setDate(fechaActual);
        
    }
    private void capturarFechaCalendar(){
                fechaActual = clFecha.getDate();
                gc.setTime(fechaActual);
                /*String fechaFormateada;
                fechaFormateada = String.valueOf(formatFecha.format(fechaActual));
                System.out.print(fechaFormateada );*/
    }
    private class ListenerCliente implements ListSelectionListener {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            int seleccion = tblVacas.getSelectedRow();
            if (seleccion != -1) {
                vacaSeleccionada = modeloTabla.getVaca(seleccion);
                cargarDatosVaca();
                btnGuardarCambios.setEnabled(true);
                btnEliminar.setEnabled(true);
                btnCancelar.setEnabled(true);
                btnAgregarNuevo.setEnabled(false);
                ddlRaza.setEnabled(false);
                ddlCategoria.setEnabled(false);
            }
        }
    }
    private void cargarDatosVaca(){
        this.txtCaravana.setText(vacaSeleccionada.getCaravana());
        this.txtPeso.setText(vacaSeleccionada.getPeso().toString());
        
        this.ddlCategoria.setSelectedItem(ABORT);
        this.ddlRaza.setSelectedItem(ABORT); //ELEGIR EL TIPO
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNuevo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCambios;
    private com.toedter.calendar.JDateChooser clFecha;
    private javax.swing.JComboBox ddlCategoria;
    private javax.swing.JComboBox ddlRaza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tblVacas;
    private javax.swing.JTextField txtCaravana;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
